# Generated by Django 6.0.1 on 2026-02-14 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_tax_id_alter_user_nid_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='consent_version',
            field=models.CharField(default='v1.0', max_length=10),
        ),
    ]
