# Generated by Django 6.0.1 on 2026-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('ZONE1', 'Zone 1 - Kigali'), ('ZONE2', 'Zone 2 - Provinces'), ('ZONE3', 'Zone 3 - EAC (International)')], max_length=10, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_multiplier', models.DecimalField(decimal_places=2, help_text='Cost per extra kg', max_digits=5)),
            ],
        ),
    ]
