# Generated by Django 6.0.1 on 2026-01-30 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_id', models.CharField(help_text='Customs Declaration Number', max_length=50, unique=True)),
                ('tin_number', models.CharField(help_text='Tax ID for trade', max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_country', models.CharField(choices=[('UG', 'Uganda'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('CD', 'DRC')], max_length=2)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_customs_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
